# Generated by Django 3.2.5 on 2021-07-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(max_length=144, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_birth',
            field=models.DateField(null=True, verbose_name='birth date'),
        ),
    ]
